full_name: 宝生玛格
font: font3.ttf
text_config:
  - text: 宝
    position: [ 759, 73 ]
    font_color: [ 185, 124, 235 ]
    font_size: 186
  - text: 生
    position: [ 945, 175 ]
    font_color: [ 255, 255, 255 ]
    font_size: 92
  - text: 玛
    position: [ 1042, 117 ]
    font_color: [ 255, 255, 255 ]
    font_size: 147
  - text: 格
    position: [ 1186, 175 ]
    font_color: [ 255, 255, 255 ]
    font_size: 92